version: '3.8'

services: 
  api:
    build: . 
    container_name: API-EXAMPLE-NEWRELIC
    environment:
      - PORT=8091
      - USER=user-test
      - PASS=123@test
    volumes:
      - .:/usr/app 
    ports:
      - "8091:8091" 